[package]
name = "sha1_cracker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha-1 = "0.9"
sha2 = "0.10"
sha256 = "1.1.1"
hex = "0.4"
egui = "0.19.0"
eframe = "0.19.0"
tracing-subscriber = "0.3"
